[manifest]
version = "1.0.0"
dump_lua = true
priority = 0



# Get last Misprint proc
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
local temp_Mult = pseudorandom('misprint', self.ability.extra.min, self.ability.extra.max)
'''
position = 'after'
payload = '''
MISPRINT_LAST_TRIGGER = temp_Mult
'''
match_indent = true