[manifest]
version = "1.0.0"
dump_lua = true
priority = 0



# Make context right before reroll
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
local final_free = G.GAME.current_round.free_rerolls > 0
'''
position = 'before'
payload = '''
for i = 1, #G.jokers.cards do
    G.jokers.cards[i]:calculate_joker({before_reroll = true})
end
'''
match_indent = true







