[manifest]
version = "1.0.0"
dump_lua = true
priority = 0



####################################################################################
# Prism Deck

# Make so suit changing tarots change enhancement

## Make all selected cards get same enhancement
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
elseif self.ability.consumeable.suit_conv then
'''
position = 'after'
payload = '''
local random_enhancement = SMODS.poll_enhancement {key = "modprefix_seed", guaranteed = true}
'''
match_indent = true



## Apply enhancement
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
G.E_MANAGER:add_event(Event({trigger = 'after',delay = 0.1,func = function() G.hand.highlighted[i]:change_suit(self.ability.consumeable.suit_conv);return true end }))
'''
position = 'after'
payload = '''
if G.GAME.selected_back.effect.center.key == "b_CTEH_prism_deck" then
    G.E_MANAGER:add_event(Event({trigger = 'after',delay = 0.1,func = function() G.hand.highlighted[i]:set_ability(random_enhancement);return true end }))
end
'''
match_indent = true



####################################################################################
# Sizaak Bus Deck



## Add Cerulean Bell selection to all bosses (G.GAME.modifiers.all_cbell logic) and it not be a sizaak card (tested, works)
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = '''
function Blind:drawn_to_hand()
    if not self.disabled then
'''
position = 'after'
payload = '''
        if G.GAME.modifiers.all_cbell and self.boss then
            local any_forced = nil
            for k, v in ipairs(G.hand.cards) do
                if v.ability.forced_selection and not SMODS.has_enhancement(v,'m_CTEH_sizaak_enh') then
                    any_forced = true
                end
            end
            if not any_forced then 
                G.hand:unhighlight_all()

                local forced_card
                repeat
                forced_card = pseudorandom_element(G.hand.cards, pseudoseed('cerulean_bell'))
                until not SMODS.has_enhancement(forced_card,'m_CTEH_sizaak_enh')                

                forced_card.ability.forced_selection = true
                G.hand:add_to_highlighted(forced_card)
            end
        end
'''
match_indent = true
