[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Edzy Joker, Blue Printer, Lucky Mirror, Artist's Leeway

####################### Edzy Joker

# Return played cards instead of discarding them
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
draw_card(G.play,G.discard, it*100/play_count,'down', false, v)
'''
position = 'at'
payload = '''
local last_joker = G.jokers.cards[#G.jokers.cards]
if last_joker and last_joker.ability.name == 'j_CTEH_edzy' and not last_joker.ability.used then 
    draw_card(G.play,G.hand, it*100/play_count,'up', false, v)
else
    draw_card(G.play,G.discard, it*100/play_count,'down', false, v)
end
'''
match_indent = true



# Activate Edzy joker
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
if G.GAME.chips - G.GAME.blind.chips >= 0 or G.GAME.current_round.hands_left < 1 then
'''
position = 'before'
payload = '''
local last_joker = G.jokers.cards[#G.jokers.cards]
if last_joker and last_joker.ability.name == 'j_CTEH_edzy' and not last_joker.ability.used then
    last_joker.ability.used = true
    card_eval_status_text(last_joker, 'extra', nil, nil, nil, {message = "Undo", colour = G.C.RED})

    G.GAME.current_round.hands_left = G.GAME.current_round.hands_left + 1
    G.GAME.current_round.hands_played = G.GAME.current_round.hands_played - 1
    G.GAME.chips = LAST_SAVED_SCORE

    local first_hand = G.GAME.current_round.hands_played == 0
    if first_hand and G.GAME.blind.name == 'The Mouth' then
        G.GAME.blind.only_hand = false
    end
    if G.GAME.blind.name == 'The Eye' then
        G.GAME.blind.hands[LAST_PLAYED_HAND] = false
    end
end
'''
match_indent = true



####################### Blue Printer

# Get last Misprint proc
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
local temp_Mult = pseudorandom('misprint', self.ability.extra.min, self.ability.extra.max)
'''
position = 'after'
payload = '''
MISPRINT_LAST_TRIGGER = temp_Mult
'''
match_indent = true



####################### Lucky Mirror

# Trigger Lucky mirror joker for each timer downtick
[[patches]]
[patches.pattern]
target = '=[SMODS Multiplayer "ui/hud.lua"]'
pattern = '''
MP.GAME.timer = MP.GAME.timer - 1
'''
position = 'after'
payload = '''
for i = 1, #G.jokers.cards do
    if G.jokers.cards[i].ability.name == 'j_CTEH_lucky_mirror' and SMODS.pseudorandom_probability(card, "lucky_mirror_timer", 1, MP.GAME.timer) then
        MP.GAME.multi_player:increase_additive_value(1)
        G.jokers.cards[i].ability.additional_probability = G.jokers.cards[i].ability.additional_probability + 1
        card_eval_status_text(G.jokers.cards[i], 'extra', nil, nil, nil, {message = "+Odds!", colour = G.C.GREEN})
    end
end
'''
match_indent = true



####################### Artist's Leeway

# Suit tarots not use up a pack choice
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
elseif G.GAME.pack_choices and G.GAME.pack_choices > 1 then
'''
position = 'before'
payload = '''
elseif next(SMODS.find_card("j_CTEH_artists_leeway")) and card.ability.consumeable and card.ability.consumeable.suit_conv then
    if G.booster_pack.alignment.offset.py then 
        G.booster_pack.alignment.offset.y = G.booster_pack.alignment.offset.py
        G.booster_pack.alignment.offset.py = nil
    end
'''
match_indent = true

