[manifest]
version = "1.0.0"
dump_lua = true
priority = 0



# Override mouse coordinates
[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''
self.cursor_position.x, self.cursor_position.y = love.mouse.getPosition()
'''
position = 'at'
payload = '''
self.cursor_position.x, self.cursor_position.y = getCursorPosition()
'''
match_indent = true



# Add CTEH settings tab
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
  local t = create_UIBox_generic_options({back_func = 'options',contents = {create_tabs(
'''
position = 'before'
payload = '''
  tabs[#tabs+1] = {
    label = 'CTEH',
    tab_definition_function = G.UIDEF.settings_tab,
    tab_definition_function_args = 'CTEH'
  }
'''
match_indent = true



# Create cursor related settings in the CTEH tab
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
  elseif tab == 'Graphics' then 
'''
position = 'before'
payload = '''
  elseif tab == 'CTEH' then 
    return {n=G.UIT.ROOT, config={align = "cm", padding = 0.05, colour = G.C.CLEAR}, nodes={
      -- TODO things should be saved in a file 
      create_slider({label = 'Sensitivity', w = 4, h = 0.4, ref_table = SMODS.Mods['CTEH'].config, ref_value = 'default_sensitivity', callback = 'reset_sensitivity', min = 0.5, max = 2, decimal_places = 2, current_option = SMODS.Mods['CTEH'].config.default_sensitivity or 1}),
      create_option_cycle({w = 4, scale = 0.8, label = 'M1 Cursor', options = {'Four Fingers','Banner','Cloud 9','Arrowhead','Gros Michel','Bootstraps','Ceremonial Dagger','Rocket','Seltzer'}, opt_callback = 'set_m1_cursor', current_option = SMODS.Mods['CTEH'].config.cursor_index or 1}),
      create_toggle({label = "Held Cursor", ref_table = SMODS.Mods['CTEH'].config, ref_value = 'is_m1_held', current_option = SMODS.Mods['CTEH'].config.is_m1_held or true}),
      create_option_cycle({w = 4, scale = 0.8, label = 'Held Cursor', options = {'Fist','Bean','Egg','Oops','Bull','8 ball','Square','Delayed Grat'}, opt_callback = 'set_m1_held_cursor', current_option = SMODS.Mods['CTEH'].config.held_cursor_index or 1}),
    }}
'''
match_indent = true


