[manifest]
version = "1.0.0"
dump_lua = true
priority = 0



####################################################################################
# Stone Seal

# Perma bonus behaviour
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.ability and old_center and old_center.config.bonus then
'''
position = 'before'
payload = '''
if behaveLikeSeal(self,'CTEH_stone') then
    self.ability.perma_bonus = self.ability.perma_bonus + 40
end
'''
match_indent = true


# Discard behaviour
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.seal == 'Purple' and #G.consumeables.cards + G.GAME.consumeable_buffer < G.consumeables.config.card_limit then
'''
position = 'before'
payload = '''
if behaveLikeSeal(self,'CTEH_stone') then
    self:set_ability('m_stone', nil, true)
end
'''
match_indent = true



####################################################################################
# Wild Seals joker

## Blue
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.seal == 'Blue' and #G.consumeables.cards + G.GAME.consumeable_buffer < G.consumeables.config.card_limit and not self.ability.extra_enhancement then
'''
position = 'at'
payload = '''
if behaveLikeSeal(self,'Blue') and #G.consumeables.cards + G.GAME.consumeable_buffer < G.consumeables.config.card_limit and not self.ability.extra_enhancement then
'''
match_indent = true


## Red
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.seal == 'Red' then
'''
position = 'at'
payload = '''
if behaveLikeSeal(self,'Red') then
'''
match_indent = true


## Purple
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.seal == 'Purple' and #G.consumeables.cards + G.GAME.consumeable_buffer < G.consumeables.config.card_limit then
'''
position = 'at'
payload = '''
if behaveLikeSeal(self,'Purple') and #G.consumeables.cards + G.GAME.consumeable_buffer < G.consumeables.config.card_limit then
'''
match_indent = true


## Gold
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
elseif self.seal == 'Gold' and not self.ability.extra_enhancement then
'''
position = 'at'
payload = '''
elseif behaveLikeSeal(self,'Gold') and not self.ability.extra_enhancement then
'''
match_indent = true



####################################################################################
# Suited Seals joker

## Red and Purple seals
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
    if card.seal then
'''
position = 'at'
payload = '''
   if isConsideredSealed(card) then
'''
match_indent = true

