SMODS.Challenge {
    key = 'sizaak_bus',
    jokers = {
        { id = 'j_ride_the_bus', eternal = true },
        { id = 'j_drivers_license', eternal = true },
    },
    rules = {
        custom = {
            { id = 'bus_debuff_license' },
            { id = 'bus16' },
            { id = 'sizaak_bus_losecon' },
{ id = 'sizaak_bus_wincon' },
            { id = 'alternate_wincon' },
            { id = 'all_cbell' },
        }
    },
    deck = {
        type = 'Challenge Deck',
        cards = {
            { s = 'C', r = 'A' },
            { s = 'D', r = 'A' },
            { s = 'H', r = 'A' },
            { s = 'S', r = 'A' },
            { s = 'C', r = 'K', e = 'm_CTEH_sizaak_enh' },
            { s = 'D', r = 'K' },
            { s = 'H', r = 'K' },
            { s = 'S', r = 'K' },
            { s = 'C', r = 'Q' },
            { s = 'D', r = 'Q' },
            { s = 'H', r = 'Q' },
            { s = 'S', r = 'Q' },
            { s = 'C', r = 'J' },
            { s = 'D', r = 'J' },
            { s = 'H', r = 'J' },
            { s = 'S', r = 'J' },
            { s = 'C', r = 'T' },
            { s = 'D', r = 'T' },
            { s = 'H', r = 'T' },
            { s = 'S', r = 'T' },
            { s = 'C', r = '9' },
            { s = 'D', r = '9' },
            { s = 'H', r = '9' },
            { s = 'S', r = '9' },
            { s = 'C', r = '8' },
            { s = 'D', r = '8' },
            { s = 'H', r = '8' },
            { s = 'S', r = '8' },
            { s = 'C', r = '7' },
            { s = 'D', r = '7' },
            { s = 'H', r = '7' },
            { s = 'S', r = '7' },
            { s = 'C', r = '6' },
            { s = 'D', r = '6' },
            { s = 'H', r = '6' },
            { s = 'S', r = '6' },
            { s = 'C', r = '5' },
            { s = 'D', r = '5' },
            { s = 'H', r = '5' },
            { s = 'S', r = '5' },
            { s = 'C', r = '4' },
            { s = 'D', r = '4' },
            { s = 'H', r = '4' },
            { s = 'S', r = '4' },
            { s = 'C', r = '3' },
            { s = 'D', r = '3' },
            { s = 'H', r = '3' },
            { s = 'S', r = '3' },
            { s = 'C', r = '2' },
            { s = 'D', r = '2' },
            { s = 'H', r = '2' },
            { s = 'S', r = '2' },
        }
    }
}